### ISSUE TITLE
Handle ks.cfg in the conversion

### ISSUE THREAD

**Issue by kbarber** [mitchellh/veewee-to-packer#1]
I did a conversion of the Centos-6.4-x86_64-netboot template, but this tool misses out copying the ks.cfg file into 'http'. Fairly easy to work around obviously :-).

**Comment by mitchellh** [comment]
Hm, it actually does this. I bet you your template was missing the "kickstart_file" parameter, which is really kind of a bug with the Veewee definition. However, maybe I can add a hardcoded "if ks.cfg, copy" thing into V2P.

**Comment by kbarber** [comment]
You know, you are right. I thought it didn't at the time, but perhaps I made a mistake. Most of the common veewee templates have the declaration, I'm going to close this - thanks @mitchellh.
