### ISSUE TITLE
Unknown keys for VirtualBox: [:iso_sha1]

### ISSUE THREAD

**Issue by TFDuesing** [mitchellh/veewee-to-packer#10]
When attempting to convert the the Fedora-19-x86_64 veewee template, veewee-to-packer throws `An error occurred: Unknown keys for VirtualBox: [:iso_sha1]`.

This is most likely related to Packer [issue #175: Allow checksums to be non-MD5 (such as SHA)](https://github.com/mitchellh/packer/issues/175).

**Comment by mitchellh** [comment]
Fixed. I can't release the fix until Packer 0.2.0 is released, which will be done shortly. (in the next week or so).
