### ISSUE TITLE
Unknown keys for VirtualBox: [:video_memory_size, :winrm_password, :winrm_user]

### ISSUE THREAD

**Issue by tduffield** [mitchellh/veewee-to-packer#12]
I'm not sure if these map to something different, but I'm having issues with my Windows definitions (spoiler alert).

**Comment by mitchellh** [comment]
Packer doesn't support winrm yet so that is okay. 

I pushed a fix and released 0.2.1 which fixes the video_memory_size issue.

WinRM will be supported in a future Packer release.
