### ISSUE TITLE
Convert <Wait> to <wait> (case-conversion)

### ISSUE THREAD

**Issue by steffenweber** [mitchellh/veewee-to-packer#15]
I was attempting to convert the following veewee definition: https://github.com/jedi4ever/veewee/blob/master/templates/gentoo-latest-amd64/definition.rb

In the "boot_cmd_sequence" I had to manually convert "<Wait>" to "<wait>" because otherwise packer would "type" them literally instead of recognizing them as wait instructions.

**Comment by mitchellh** [comment]
Fixed and released v0.2.6. Thanks!
