### ISSUE TITLE
Handle conversion of OS identifiers based on provider

### ISSUE THREAD

**Issue by smerrill** [mitchellh/veewee-to-packer#4]
Veewee has a feature where it will take a machine's `:os_type_id` and convert it to one value for VirtualBox and another for VMware Fusion. For example, if your definition.rb has an `:os_type_id` of `RedHat6_64`, Veewee will convert it to `rhel6-64` for VMWare Fusion or `RedHat_64` for VirtualBox.

(See https://github.com/jedi4ever/veewee/blob/9455e1d7918b7838700455d9f41f1d41083c209f/lib/veewee/config/ostypes.yml#L207 )

It would be ideal to do this or put in some documentation so that people converting veewee templates do not scratch their heads when VMWare Fusion complains that it doesn't know the 'RedHat6_64' operating system.

**Comment by mitchellh** [comment]
V2P already does this: https://github.com/mitchellh/veewee-to-packer/blob/master/lib/veewee-to-packer/builders/vmware.rb#L107
