### ISSUE TITLE
veewee-to-packer cannot handle links

### ISSUE THREAD

**Issue by till** [mitchellh/veewee-to-packer#5]
Trying to convert a bento setup to packer. And this gem fails to load a file which is _there_. I think it may be because it's just linked and not an actual file.

```
veewee-to-packer my-def/definition.rb
An error occurred:

Error loading input template: cannot load such file -- my-def/../.ubuntu/session.rb
```

When I go into `my-def`, it fails with:

```
veewee-to-packer definition.rb
An error occurred:

Uknown keys: [:virtualbox]
```

(There is also a typo in the error message.)

**Comment by mitchellh** [comment]
Fixed I think. Try 0.1.3. Released now.

**Comment by till** [comment]
:+1: Thanks!
