### ISSUE TITLE
Unknown keys: [:hwvirtext] in VMware

### ISSUE THREAD

**Issue by neil477** [mitchellh/veewee-to-packer#8]
get this when I run veewee-to-packer on the definition.rb for the vewee template Fedora-17-x86_64 in the repo

**Comment by mitchellh** [comment]
That is because "hwvirtext" is actually incorrect. It should be `hwvirtex`. This is a bug in the template itself. :)

**Comment by neil477** [comment]
Upon making the changes, I know get:

An error occurred:
Uknown keys: [:hwvirtex]

Thats right, "Uknown" keys too. Couldn't find that error when I grepped through the source of veewee-to-packer though.

**Comment by mitchellh** [comment]
Are you using the latest version of v2p?

This was fixed in around 0.1.2 or so. Can you run "gem list" to check?

**Comment by neil477** [comment]
on running gem list I get

veewee-to-packer (0.1.4)

**Comment by mitchellh** [comment]
AH! Is this for the VMware builder? Do you get the output if you specify `--builders=virtualbox`?

**Comment by neil477** [comment]
yup works now! How'd you know it was for vmware?

**Comment by mitchellh** [comment]
Haha, just running through the code I couldn't see how the virtualbox one wasn't working. I'm going to reopen this issue and mark that this needs to be done for VMware.

**Comment by mitchellh** [comment]
Released 0.1.5 which fixes this
